>H._sapiens_original
MAPSSKSERNSGAGSGGGGPGGAGGKRAAGRRREHVLKQLERVKISGQLSPRLFRKLPPR
	VCVSLKNIVDEDFLYAGHIFLGFSKCGRYVLSYTSSSG-DDDFSFYIYHLYWWEFNVHS
K	LKLVRQVRLFQDEEIYSDLYLTVCEWPSDASKVIVFGFNTRSANGMLMNMMMMSDENH
RD	IYVSTVAVPPPGRCAACQDASR-AHPDPNAQCLRHGFMLHTKYQVVYPFPTFQPAFQ
LKK	DQVVLLNTSYSLVACAVSVHSAGDRSFC---QILYDHSTCP--LAPASPPEPQ---
----	------SPELPPALPSFCPEAAPARSSGSPEPSPAIAKAKEFVADIFRRAKEAKG
G----	--------------------VPEEARPALCPGPSGSRCRAHS--------EPLA
LC----	--------GETAPRDSPPASEAPASEPGYVNYTKLYYVLESGEGTEPEDELED
DKISLPF	VVTDLRGRNLRPMRERTAVQGQYLTVEQLTLDFEYVINEVIRHDATWGHQFC
SFSDYDIV	ILEVCPETNQVLINIGLLLLAFPSPTEEGQLRPKTYHTSLKVAWDLNTGIF
ETVSVGDLT	EVKGQT-------SGSVW---SSYRKSCVDMVMKWLVPESSGRYVNRMTN
EALHKGCSLK	VLADSERYTWIVL---------	
>D._rerio
------------------------------------------------------------
	-----------------------------------------------------------
-	----------------------------------------------------------
--	---------------------------------------------------------
---	--------------------------------------------------------
----	----------------------------------------VGPDSRDRRAQAGAR
EPERC	KTKEKEETDTQRRLHDEERTRE---SPREVPGPSSSSSEPNQSSV-----VESG
VCNAIV	SPRSTSSVSSPSPHEQEPSSSSSSSEPAYVNYTTLRYRLPQATAVEESNGEED
DKVQLPF	TVTDLKGRPLQLVTG--QYSGQFVCIEQLTLDFEYLINEVIRNDAEWGSQFC
SFSDYDVV	ILEVCPETNIVVINIGLLLLAFSNC-DDEHCRPSRITP-----------VC
MSVGI*TQA	RVTQLGSATSLSQRSDQWKCVELYRKSCVIL*CGGSCRKAAQLLTHDMSL
A*AL-LSV*L	NMTEALESSW*FIQGILGTASN	
>S._grahami
MAASTKSEKDD------------NKQKQQKKHKDHIVKLLTRGRLNGQLSQRLFRKLPPR
	VCIPLKTIVSEEFLRAGHIFLGFTKCGRYVLSYTSDCGEDDDFSFYTYHLYWWEFNLHS
R	LKQVHHVRLFAGEDIYSDLYLTVCEWHNDHSKLVIFGFNTRSSSSALMNMM-MSDENN
RD	IYITITSMPPAQPCKQCCPASSVSTIRTGGECLQHGYVLNARYQVVYPFPTFQPALQ
LKK	DQVILLNTSYSLVACAISLCSGDGQQEGQNNQILYRKRDASSSSPPAGPTSPSSSS
-S--	-TSSQGSPDLRQLKPLFT--------PLSSGQSQAAARAREFAADIFRRAQTGTR
EHDR-	KAKEKEEMDPQRFHSEEERTRERQERDAEVPGPSSSFSGQNQSSVSPTEAEDSA
VCNANM	SPGSISSVSSLSPHAHEPSSSSSSSEPAYVNYTTLRYRLPQARAPEQPSGDED
DKVLLPF	TVTDLKGRNLQLVTG--QFSGQCVCVEQLTLDFEYLINEVIRNDADWGSQFC
SFSDYDVV	ILEVCPETNIVVINIGLLLLAFSNC-EDEHCRPKSYHSSLQVSWDLNTGAC
RTVGVSDLT	EVKGQT-------SGSVW---SSYRKSCVNTVMRWLVPESSSRYINRMTN
EALHKGSSLQ	VLADNDRGTWIVL---------	
>C._carpio
MAPSSKSEKDD------------NKQKQQKKHKDHVVKLLTRGRLNGHLSQRLFRKLPPR
	VCIPLKTIVSEEFLRAGHIFLGFTKCGRYVLSYTSDCGEDDDFSFYTYHLYWWEFNLHS
R	LKQVHHVRLFAGEDIYSDLYLTVCEWHNDHSKLVVFGFNTRSSSSALMNMM-MSDENN
RD	IYITITSMPPAQPCKQCCPASSVSTIRTGGECLQHGYVLNARYQVVYPFPTFQPALQ
LKK	DQVILLNTSYSLVACAISLCSGDGQQEDQNNQILYRKGDASSSSPPVGPTSPSSSS
-S--	-TSSQGSPDLTQLKPHFT--------PLSSSQSQAAVRAREFAADIFRRAQAGAT
EHDR-	KAKEKEETDTQRFHSEEERTRERQERDAEVPGPSSSSSGQNQSSVPPTEAEDSA
VCNTVM	SPGSTSSLFSLSPHAHEPSSSSSSSEPAYVNYTTLRYRLPQASASEQLSGDED
DKVLLPF	TVTDLKGRNLQLVTG--QFSGQCVCVEQLTLDFEYLINEVIRNDADWGSQFC
SFSDYDVV	ILEVCPETNIVVINIGLLLLAFSNC-EDEHCRPKSYHSSLQVSWDLNTGAC
HTVGVGDLT	EVKGQT-------SGSVW---SSYRKSCVNTVMRWLVPESSSRYINRMTN
EALHKGSSLQ	VLADNDRGTWIVL---------	
>A._grahami
MAPSSKSEKDD------------NKQKQQRKHKDHVIKLLTRGRLNGQLSQRLFRKLPPR
	VCVPLKTIVSEEFLRAGHIFLGFTKCGRYVLSYTSDCGEDDDFSFYTYHLYWWEFNLHS
R	LKQVHHVRLFAGEDIYTDLYLTVCEWHNDHSKLVIFGFNTRSSSSALMNMM-MSDENN
RD	IYITITSMPPAQPCKQCCPTSSVSTIRTGGECLQHGYVLNARYQVVYPFPTFQPALQ
LKK	DQVILLNTSYSLVACAISLCPGDGQQDCQNNQILYRKREASSSSPPAGPMSPSSSS
SSSS	STSSEESSNLRQSKPHFT--------PLSPGQSQAAVRAREFAADIFRRAQAGTR
EHDRC	KAKEKEETDTQRFPSEEDRTTEGHERDAEVPGPSSSSSGENQCSVPPTEADEST
VCNTVM	SPGSTSSVSSLSPHAHEPSSSSSSSEPSYVNYTTLRYRLPQAGAAEQPSGEED
DKVQLPF	TVTDLKGRNLQLVTG--QYSGQCVCIEQLTLDFEYLINEVIRNDADWGSQFC
SFSDYDVV	ILEVCPETNKVVINIGLLLLAFSNC-EDEHCRPKSYHSSLQVSWDLNTGAC
HTVGVGDLT	EVKGQT-------SGSVW---SSYRKSCVNTVMRWLVPESSSRYINRMTN
EAMHKGVVYT	DTCA------------------	
>C._auratus
MAPSSKSEKND------------NKQKQLKKHKDHVVKLLTRGRLNGHLSQRLFRKLPPR
	VCVPLKTIVSEEFLRAGHIFLGFTKCGRYVLSYTSDCGEDDDFSFYTYHLYWWEFNLHS
R	LKQVHHVRLFAGEDIYSDLYLTVCEWHHDHSKLVVFGFNTRSSSSALMNMM-MSDENN
RD	IYITITSMPPAQPCKQCCPASSVSTIRTGGECLQHGYVLNARYQVVYPFPTFQPALQ
LKK	DQVILLNTSYSLVACAISLCSGDGHQEGQNNQILYRKRDASSSSAPVGPTSPSSSS
-S--	-TSSQGSPDLRQLKPHFT--------PLSSSQSQAAVRAREFAADIFRRAQAGAR
EHDR-	KNKEKEETDTQRFHSEEERMRETQECDAEVPGPSSSSSGQNQGSVLPTDAEDSA
VCNTVM	SPGSTSSVFSLSPRPHEPSSSSSSSEPAYVNYTTLRYRLPQASASEQPSGDED
DKVLLPF	TVTDLKGRNLQLVTG--QFSGQCVCVEQLTLDFEYLINEVIRNDADWGSQFC
SFSDYDVV	ILEVCPETNIVVINIGLLLLAFSNC-EDEHCRPKSYHSSLQVSWDLNTGAC
RTVGVGDLT	EVKGQT-------SGSVW---SSYRKSCVNTVMRWLVPESSSRYINRMTN
EALHKGSSLQ	VLADNDRATWIVL---------	
>P._tetrazona
MAPSSKSEKDD------------NKQKQQKKHKDHVVKLLTRGRLNGHLSQRLFRKLPPR
	VCVPLKTIVSEEFLRAGHIFLGFTKCGRYVLSYTSDCGEDDDFSFYTYHLYWWEFNLHS
R	LKQVHHVRLFAGEDIYSDLYLTVCEWHNDHSKLVVFGFNTRSSSSALMNMM-MSDENN
RD	IYITITSMPPAQPCKQCCPASPASTIRTGGECLQHGYVLNARYQVVYPFPTFQPALQ
LKK	DQVILLNTSYSLVACAISLCSGDGQQDGQTNQILYHKRDASSSSPPAGPTSPSSSS
SS--	-ASSQGSPDLRQLKPHFA--------PLSSSQSQAAVRAREFAADIFRRAQAGAR
EHDR-	KAKEKEETDAQRVHGEEE----KQERDAEVPGPSSSSSGR--SSVRAAEAVDGA
ACSAVR	SPGSTSSVSSLSPHAHEPSSSSSSSEPAYVNYTTLRYRLPQGRASEQPSGDED
DKVLLPF	TVTDLKGRNLQLVTG--QFSGQCVCIEQLTLDFEYLINEVIRNDADWGSQFC
SFSDYDVV	ILEVCPETNIVVINIGLLLLAFSNC-EDEHCRPKSYHSSLQVSWDLNTGAC
RTVGVGDLT	EVKGQT-------SGSVW---SSYRKSCVNTVMRWLVPESSSRYINRMTN
EALHKGSSLQ	VLADNDRGTWIVL---------	
